### ISSUE TITLE
To allow the KSM Install Images to be pushed to the private registry you need to have created a project call container-services-manager

### ISSUE THREAD

**Issue by pivot-man** [pivotal-cf/docs-ksm#77]
For the 'Move KSM Images' Step 3. Push the images to your registry by running these commands:

`docker push REGISTRY/container-services-manager/broker:VERSION-NUMBER`

If you use Harbor you need to have created a project with name **container-services-manager** for this step to work.

Otherwise, you get the following error:

`denied: requested access to the resource is denied`

**Comment by snneji** [comment]
I thanks letting us know about this. I'll pass the information on to the KSM team and make sure the docs get updated.

**Comment by snneji** [comment]
Hi @pivot-man, we have merged a PR to the docs that deals with this issue and we hope to publish the change soon. Thanks for taking the time to alert us about this issue.
